"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/toaster";
import { PayPalScriptProvider } from "@paypal/react-paypal-js";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { type ThemeProviderProps } from "next-themes";
import { WishlistProvider } from "@/context/wishlist-provider";

const inter = Inter({ subsets: ["latin"] });

import type { ReactNode } from "react";
import type { Session } from "next-auth";
import { AuthProvider } from "@/context/authContext";

// ThemeProvider wrapper
function ThemeProvider({ children, ...props }: ThemeProviderProps) {
  return <NextThemesProvider {...props}>{children}</NextThemesProvider>;
}

// AppProviders wrapper
function AppProviders({ children, session }: { children: ReactNode; session: Session | null }) {
  return (
    <SessionProvider session={session}>
      <AuthProvider>
        <PayPalScriptProvider options={{ clientId: process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID || "" }}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </PayPalScriptProvider>
      </AuthProvider>
    </SessionProvider>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <body className={inter.className}>
        <AppProviders session={null}>
          <WishlistProvider>
          <Header />
          <main>{children}</main>
          <Footer />
           </WishlistProvider>
          <Toaster />
        </AppProviders>
      </body>
    </html>
  );
}















// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Providers from "./provider";
// import Header from "./components/header";
// import Footer from "./components/footer";
// import { WishlistProvider } from "@/context/wishlist-provider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
      
//       <body className={inter.className}>
        
//         <Providers>
//         <WishlistProvider>
//       <Header/>
      
//         {children}
        
//         <Footer/>
//         </WishlistProvider>
//         </Providers>
      
//         </body>
//     </html>
//   );
// }
